https://www.kaggle.com/andresionek/joining-marketing-funnel-with-brazilian-e-commerce

In [2]:
import numpy as np
import pandas as pd
import os

In [3]:
print('### Marketing Funnel by Olist ###')
for idx, file in enumerate(os.listdir('Data/Marketing')):
    print(idx, '-', file)
print('\n---------------------------------------------\n')

print('### Brazilian E-Commerce Public Dataset by Olist ###')
for idx, file in enumerate(os.listdir('Data/E-Commerce')):
    print(idx, '-', file)

### Marketing Funnel by Olist ###
0 - olist_closed_deals_dataset.csv
1 - olist_marketing_qualified_leads_dataset.csv

---------------------------------------------

### Brazilian E-Commerce Public Dataset by Olist ###
0 - olist_customers_dataset.csv
1 - olist_geolocation_dataset.csv
2 - olist_orders_dataset.csv
3 - olist_order_items_dataset.csv
4 - olist_order_payments_dataset.csv
5 - olist_order_reviews_dataset.csv
6 - olist_products_dataset.csv
7 - olist_sellers_dataset.csv
8 - product_category_name_translation.csv

## Marketing data set

In [5]:
mql = pd.read_csv('Data/Marketing/olist_marketing_qualified_leads_dataset.csv')
cd = pd.read_csv('Data/Marketing/olist_closed_deals_dataset.csv')

In [6]:
# marketing funnel dataset (NaNs are leads that did not close a deal)
mf = mql.merge(cd, on='mql_id', how='left')
mf.head(10)

,mql_id,first_contact_date,landing_page_id,origin,seller_id,sdr_id,sr_id,won_date,business_segment,lead_type,lead_behaviour_profile,has_company,has_gtin,average_stock,business_type,declared_product_catalog_size,declared_monthly_revenue
0,dac32acd4db4c29c230538b72f8dd87d,2018-02-01,88740e65d5d6b056e0cda098e1ea6313,social,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,8c18d1de7f67e60dbd64e3c07d7e9d5d,2017-10-20,007f9098284a86ee80ddeb25d53e0af8,paid_search,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,b4bc852d233dfefc5131f593b538befa,2018-03-22,a7982125ff7aa3b2054c6e44f9d28522,organic_search,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6be030b81c75970747525b843c1ef4f8,2018-01-22,d45d558f0daeecf3cccdffe3c59684aa,email,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5420aad7fec3549a85876ba1c529bd84,2018-02-21,b48ec5f3b04e9068441002a19df93c6c,organic_search,2c43fb513632d29b3b58df74816f1b06,a8387c01a09e99ce014107505b92388c,4ef15afb4b2723d8f3d81e51ec7afefe,2018-02-26 19:58:54,pet,online_medium,cat,NaN,NaN,NaN,reseller,NaN,0.0
5,28bdfd5f057764b54c38770f95c69f2f,2018-01-14,22c29808c4f815213303f8933030604c,organic_search,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,126a0d10becbaafcb2e72ce6848cf32c,2018-05-15,6a110e795dd487f1cf8d7583671987af,email,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,f76136f54d14a3345951f25b7932366b,2018-05-24,d51b0d02f063ba1d053db6d97226eec3,email,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2f838cade4a6012a6cb1016d1d8d95ed,2017-11-10,aeac92c0f5ae22a04ed3b746cce3a1b6,organic_search,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,7281942387a1a0c3f72a50a8b0bb0920,2017-12-25,88740e65d5d6b056e0cda098e1ea6313,social,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## E-commerce Dataset

In [7]:
sellers = pd.read_csv('Data/E-Commerce/olist_sellers_dataset.csv')

In [8]:
# marketing funnel merged with sellers (this way you get seller location)
mf_sellers = mf.merge(sellers, on='seller_id', how='left')

In [9]:
# order items dataset
items = pd.read_csv('Data/E-Commerce/olist_order_items_dataset.csv')

In [12]:
# marketing funnel merged with items (this way you get products sold by sellers)
products_by_sellers = mf.merge(items, on='seller_id', how='left')

In [18]:
products_by_sellers['Closed'] = products_by_sellers['seller_id'].isna().map(lambda x : 0 if x==True else 1)

In [19]:
products_by_sellers.to_csv('products_by_sellers.csv', index=False)